-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-11-22 15:49:31 GMT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

DROP TABLE City;
DROP TABLE Country;
DROP TABLE Forecast;


CREATE
  TABLE City
  (
    City_ID            INTEGER NOT NULL ,
    CityName           VARCHAR2 (30 CHAR) NOT NULL ,
    CityLocation       VARCHAR2 (30 CHAR) NOT NULL ,
    Country_Country_ID INTEGER NOT NULL
  ) ;
ALTER TABLE City ADD CHECK ( CityLocation IN ('East', 'North', 'South')) ;
ALTER TABLE City ADD CONSTRAINT City_PK PRIMARY KEY ( City_ID,
Country_Country_ID ) ;

INSERT INTO City VALUES(1, 'London', 'South', 1);


CREATE
  TABLE Country
  (
    Country_ID  INTEGER NOT NULL ,
    CountryName VARCHAR2 (30 CHAR) NOT NULL
  ) ;
ALTER TABLE Country ADD CONSTRAINT Country_PK PRIMARY KEY ( Country_ID ) ;

INSERT INTO Country VALUES(1, 'England');

CREATE
  TABLE Forecast
  (
    Forecast_ID             INTEGER NOT NULL ,
    WeatherForecast         VARCHAR2 (30 CHAR) NOT NULL ,
    MinTemp                 INTEGER NOT NULL ,
    MaxTemp                 INTEGER NOT NULL ,
    WindSpeed               INTEGER NOT NULL ,
    WindDirection           VARCHAR2 (30 CHAR) NOT NULL ,
    City_City_ID            INTEGER NOT NULL ,
    City_Country_Country_ID INTEGER NOT NULL
  ) ;

INSERT INTO Forecast VALUES(1, 'Rain', 3, 15, 30, 'Northeast', 1, 1);  

ALTER TABLE Forecast ADD CONSTRAINT Weather_Forecast CHECK ( WeatherForecast IN
('Cloudy', 'Rain', 'Snow', 'Sunshine', 'Windy')) ;
ALTER TABLE Forecast ADD CONSTRAINT Min_Temp CHECK ( MinTemp > -51) ;
ALTER TABLE Forecast ADD CONSTRAINT Max_Temp CHECK ( MaxTemp < 101) ;
ALTER TABLE Forecast ADD CHECK ( WindSpeed BETWEEN 0 AND 10) ;
ALTER TABLE Forecast ADD CONSTRAINT Wind_Direction CHECK ( WindDirection IN (
'East', 'North', 'Northeast', 'Northwest', 'South', 'Southeast', 'Southwest',
'West')) ;
ALTER TABLE Forecast ADD CONSTRAINT Weather_PK PRIMARY KEY ( Forecast_ID ) ;


ALTER TABLE City ADD CONSTRAINT City_Country_FK FOREIGN KEY (
Country_Country_ID ) REFERENCES Country ( Country_ID ) ;

ALTER TABLE Forecast ADD CONSTRAINT Weather_City_FK FOREIGN KEY ( City_City_ID,
City_Country_Country_ID ) REFERENCES City ( City_ID, Country_Country_ID ) ;

SELECT * FROM Forecast 
INNER JOIN Country ON Forecast.City_Country_Country_ID = Country.Country_ID 
INNER JOIN City ON Forecast.City_City_ID = City.City_ID ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
